name: Documentation

on:
  push:
  workflow_dispatch:
  pull_request:
  repository_dispatch:
    types: [ release ]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build docs"
    env:
      # `uv pip ...` requires venv by default. This skips that requirement.
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          git clone https://github.com/xopt-org/xopt.git
          cd xopt
          uv pip install ".[doc]"
      - name: Build Docs
        shell: bash -l {0}
        run: mkdocs build
      - name: Extract examples
        shell: bash -l {0}
        run: |
          zip -r xopt-examples.zip docs/examples/
          mv xopt-examples.zip ./site/assets/
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
  deploy:
    if: ${{ github.repository_owner == 'xopt-org' && (github.ref == 'refs/heads/main') }}
    needs: build
    name: "Deploy docs"

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment # TODO: set environment and url
#    environment:
#      name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
